export const PRICELIST = [
  {
    No: 1,
    "Service Category": "Vascular Studies",
    "Service Code": 93880,
    "Service Description":
      "Ultrasound scanning of blood flow (outside the brain) on both sides of head and neck",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Vascular Studies",
    "Service Code": 93922,
    "Service Description":
      "Ultrasound study of arteries of both arms and legs, limited",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Vascular Studies",
    "Service Code": 93923,
    "Service Description":
      "Ultrasound study of arteries of both arms and legs, complete",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 4,
    "Service Category": "Vascular Studies",
    "Service Code": 93925,
    "Service Description":
      "Ultrasound study of arteries and arterial grafts of both legs",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 5,
    "Service Category": "Vascular Studies",
    "Service Code": 93926,
    "Service Description":
      "Ultrasound study of arteries and arterial grafts of one leg or limited",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 6,
    "Service Category": "Vascular Studies",
    "Service Code": 93930,
    "Service Description":
      "Ultrasound study of arteries and arterial grafts of both arms",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 7,
    "Service Category": "Vascular Studies",
    "Service Code": 93931,
    "Service Description":
      "Ultrasound study of arteries and arterial grafts of one arm or limited",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 8,
    "Service Category": "Vascular Studies",
    "Service Code": 93970,
    "Service Description":
      "Ultrasound scan of veins of both arms or legs with pressure and movement",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 9,
    "Service Category": "Vascular Studies",
    "Service Code": 93971,
    "Service Description":
      "Ultrasound scan of veins of one arm or leg with pressure and movement",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 10,
    "Service Category": "Vascular Studies",
    "Service Code": 93975,
    "Service Description":
      "Ultrasound scan of abdominal, pelvic, and/or scrotal blood flow",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 11,
    "Service Category": "Vascular Studies",
    "Service Code": 93976,
    "Service Description":
      "Ultrasound limited scan of abdominal, pelvic, and/or scrotal blood flow",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 12,
    "Service Category": "Vascular Studies",
    "Service Code": 93978,
    "Service Description":
      "Ultrasound scan of vena cava or groin graft or vessel blood flow",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 13,
    "Service Category": "Vascular Studies",
    "Service Code": 93990,
    "Service Description": "Ultrasound of dialysis access",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Radiology Services",
    "Service Code": 70110,
    "Service Description": "X-ray of mandible, minimum of 4 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Radiology Services",
    "Service Code": 70140,
    "Service Description": "X-ray of bones of face, less than 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Radiology Services",
    "Service Code": 70150,
    "Service Description": "X-ray of bones of face, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 4,
    "Service Category": "Radiology Services",
    "Service Code": 70160,
    "Service Description": "X-ray exam of nasal bones",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 5,
    "Service Category": "Radiology Services",
    "Service Code": 70200,
    "Service Description": "X-ray of eye sockets, minimum of 4 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 6,
    "Service Category": "Radiology Services",
    "Service Code": 70210,
    "Service Description": "X-ray of paranasal sinus, less than 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 7,
    "Service Category": "Radiology Services",
    "Service Code": 70220,
    "Service Description":
      "X-ray of paranasal sinus, complete, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 8,
    "Service Category": "Radiology Services",
    "Service Code": 70250,
    "Service Description": "X-ray exam of skull",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 9,
    "Service Category": "Radiology Services",
    "Service Code": 70260,
    "Service Description": "X-ray of skull, complete, minimum of 4 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 10,
    "Service Category": "Radiology Services",
    "Service Code": 70360,
    "Service Description": "X-ray exam of neck",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 11,
    "Service Category": "Radiology Services",
    "Service Code": 70450,
    "Service Description": "CT scan head or brain",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 12,
    "Service Category": "Radiology Services",
    "Service Code": 70460,
    "Service Description": "CT scan head or brain with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 13,
    "Service Category": "Radiology Services",
    "Service Code": 70470,
    "Service Description": "CT scan head or brain before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 14,
    "Service Category": "Radiology Services",
    "Service Code": 70480,
    "Service Description": "CT scan of eye/ear",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 15,
    "Service Category": "Radiology Services",
    "Service Code": 70481,
    "Service Description": "CT scan of eye/ear with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 16,
    "Service Category": "Radiology Services",
    "Service Code": 70482,
    "Service Description":
      "CT scan of cranial cavity before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 17,
    "Service Category": "Radiology Services",
    "Service Code": 70486,
    "Service Description": "CT scan of face",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 18,
    "Service Category": "Radiology Services",
    "Service Code": 70487,
    "Service Description": "CT scan of face with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 19,
    "Service Category": "Radiology Services",
    "Service Code": 70488,
    "Service Description": "CT scan of face before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 20,
    "Service Category": "Radiology Services",
    "Service Code": 70490,
    "Service Description": "CT scan of neck",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 21,
    "Service Category": "Radiology Services",
    "Service Code": 70491,
    "Service Description": "CT scan of neck with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 22,
    "Service Category": "Radiology Services",
    "Service Code": 70492,
    "Service Description": "CT scan of neck before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 23,
    "Service Category": "Radiology Services",
    "Service Code": 70496,
    "Service Description": "CT scan of blood vessel of head with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 24,
    "Service Category": "Radiology Services",
    "Service Code": 70498,
    "Service Description": "CT scan of neck blood vessels with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 25,
    "Service Category": "Radiology Services",
    "Service Code": 70540,
    "Service Description": "MRI scan bones of the eye, face, and/or neck",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 26,
    "Service Category": "Radiology Services",
    "Service Code": 70542,
    "Service Description": "MRI Orbits with Contrast Only - MRI Face Neck Orbi",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 27,
    "Service Category": "Radiology Services",
    "Service Code": 70543,
    "Service Description":
      "MRI scan bones of the eye, face, and/or neck before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 28,
    "Service Category": "Radiology Services",
    "Service Code": 70544,
    "Service Description": "MRA scan of head blood vessels",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 29,
    "Service Category": "Radiology Services",
    "Service Code": 70545,
    "Service Description": "MRA scan of head blood vessels with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 30,
    "Service Category": "Radiology Services",
    "Service Code": 70546,
    "Service Description":
      "MRA scan of head blood vessels before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 31,
    "Service Category": "Radiology Services",
    "Service Code": 70547,
    "Service Description": "MRA scan of neck blood vessels",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 32,
    "Service Category": "Radiology Services",
    "Service Code": 70549,
    "Service Description":
      "MRA scan of neck blood vessels before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 33,
    "Service Category": "Radiology Services",
    "Service Code": 70551,
    "Service Description": "MRI scan brain",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 34,
    "Service Category": "Radiology Services",
    "Service Code": 70552,
    "Service Description": "MRI Sinus with Contrast Only",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 35,
    "Service Category": "Radiology Services",
    "Service Code": 70553,
    "Service Description": "MRI scan of brain before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 36,
    "Service Category": "Radiology Services",
    "Service Code": 71045,
    "Service Description": "X-ray of chest, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 37,
    "Service Category": "Radiology Services",
    "Service Code": 71046,
    "Service Description": "XR Chest 2 Views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 38,
    "Service Category": "Radiology Services",
    "Service Code": 71100,
    "Service Description": "X-ray of ribs of one D31side of body, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 39,
    "Service Category": "Radiology Services",
    "Service Code": 71120,
    "Service Description": "X-ray of breast bone, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 40,
    "Service Category": "Radiology Services",
    "Service Code": 71250,
    "Service Description": "CT scan chest",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 41,
    "Service Category": "Radiology Services",
    "Service Code": 71260,
    "Service Description": "CT scan chest with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 42,
    "Service Category": "Radiology Services",
    "Service Code": 71270,
    "Service Description": "CT scan chest before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 43,
    "Service Category": "Radiology Services",
    "Service Code": 71275,
    "Service Description": "CT scan of blood vessels in chest with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 44,
    "Service Category": "Radiology Services",
    "Service Code": 71552,
    "Service Description": "MRI scan of chest before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 45,
    "Service Category": "Radiology Services",
    "Service Code": 71555,
    "Service Description": "MRI scan of blood vessels of chest",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 46,
    "Service Category": "Radiology Services",
    "Service Code": 72020,
    "Service Description": "X-ray of spine, 1 view",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 47,
    "Service Category": "Radiology Services",
    "Service Code": 72040,
    "Service Description": "X-ray of spine of neck, 2 or 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 48,
    "Service Category": "Radiology Services",
    "Service Code": 72050,
    "Service Description": "X-ray of upper spine, 4 or 5 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 49,
    "Service Category": "Radiology Services",
    "Service Code": 72052,
    "Service Description": "X-ray of upper spine, 6 or more views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 50,
    "Service Category": "Radiology Services",
    "Service Code": 72070,
    "Service Description": "X-ray of middle spine, 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 51,
    "Service Category": "Radiology Services",
    "Service Code": 72080,
    "Service Description": "X-ray of middle and lower spine, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 52,
    "Service Category": "Radiology Services",
    "Service Code": 72081,
    "Service Description": "X-ray of entire spine, 1 view",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 53,
    "Service Category": "Radiology Services",
    "Service Code": 72082,
    "Service Description": "X-ray of entire spine, 2 or 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 54,
    "Service Category": "Radiology Services",
    "Service Code": 72100,
    "Service Description": "X-ray of lower back spine, 2 or 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 55,
    "Service Category": "Radiology Services",
    "Service Code": 72110,
    "Service Description": "X-ray of lower back spine, minimum of 4 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 56,
    "Service Category": "Radiology Services",
    "Service Code": 72114,
    "Service Description":
      "X-ray lower back spine including bending views minimum 6 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 57,
    "Service Category": "Radiology Services",
    "Service Code": 72125,
    "Service Description": "CT scan of upper spine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 58,
    "Service Category": "Radiology Services",
    "Service Code": 72128,
    "Service Description": "CT scan of middle spine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 59,
    "Service Category": "Radiology Services",
    "Service Code": 72131,
    "Service Description": "CT scan of lower spine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 60,
    "Service Category": "Radiology Services",
    "Service Code": 72132,
    "Service Description": "CT scan of lower spine with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 61,
    "Service Category": "Radiology Services",
    "Service Code": 72141,
    "Service Description": "MRI scan of upper spinal canal",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 62,
    "Service Category": "Radiology Services",
    "Service Code": 72146,
    "Service Description": "MRI scan of middle spinal canal",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 63,
    "Service Category": "Radiology Services",
    "Service Code": 72148,
    "Service Description": "MRI scan of lower spinal canal",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 64,
    "Service Category": "Radiology Services",
    "Service Code": 72156,
    "Service Description":
      "MRI scan of upper spinal canal before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 65,
    "Service Category": "Radiology Services",
    "Service Code": 72157,
    "Service Description":
      "MRI scan of middle spinal canal before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 66,
    "Service Category": "Radiology Services",
    "Service Code": 72158,
    "Service Description":
      "MRI scan of lower spinal canal before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 67,
    "Service Category": "Radiology Services",
    "Service Code": 72170,
    "Service Description": "X-ray of pelvis, 1 or 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 68,
    "Service Category": "Radiology Services",
    "Service Code": 72190,
    "Service Description": "X-ray of pelvis, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 69,
    "Service Category": "Radiology Services",
    "Service Code": 72192,
    "Service Description": "CT scan pelvis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 70,
    "Service Category": "Radiology Services",
    "Service Code": 72193,
    "Service Description": "CT scan pelvis with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 71,
    "Service Category": "Radiology Services",
    "Service Code": 72195,
    "Service Description": "MRI scan of pelvis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 72,
    "Service Category": "Radiology Services",
    "Service Code": 72197,
    "Service Description": "MRI scan of pelvis before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 73,
    "Service Category": "Radiology Services",
    "Service Code": 72198,
    "Service Description": "MRA scan of pelvic blood vessels",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 74,
    "Service Category": "Radiology Services",
    "Service Code": 72202,
    "Service Description": "X-ray of sacroiliac joints, 3 or more views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 75,
    "Service Category": "Radiology Services",
    "Service Code": 72220,
    "Service Description": "X-ray of tailbone, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 76,
    "Service Category": "Radiology Services",
    "Service Code": 72265,
    "Service Description": "X-ray of lower spinal canal",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 77,
    "Service Category": "Radiology Services",
    "Service Code": 73000,
    "Service Description": "X-ray of collar bone",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 78,
    "Service Category": "Radiology Services",
    "Service Code": 73010,
    "Service Description": "X-ray of shoulder blade",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 79,
    "Service Category": "Radiology Services",
    "Service Code": 73020,
    "Service Description": "X-ray of shoulder, 1 view",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 80,
    "Service Category": "Radiology Services",
    "Service Code": 73030,
    "Service Description": "X-ray of shoulder, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 81,
    "Service Category": "Radiology Services",
    "Service Code": 73040,
    "Service Description": "X-ray of shoulder with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 82,
    "Service Category": "Radiology Services",
    "Service Code": 73060,
    "Service Description": "X-ray of upper arm, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 83,
    "Service Category": "Radiology Services",
    "Service Code": 73070,
    "Service Description": "X-ray of elbow, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 84,
    "Service Category": "Radiology Services",
    "Service Code": 73080,
    "Service Description": "X-ray of elbow, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 85,
    "Service Category": "Radiology Services",
    "Service Code": 73090,
    "Service Description": "X-ray of forearm, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 86,
    "Service Category": "Radiology Services",
    "Service Code": 73100,
    "Service Description": "X-ray of wrist, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 87,
    "Service Category": "Radiology Services",
    "Service Code": 73110,
    "Service Description": "X-ray of wrist, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 88,
    "Service Category": "Radiology Services",
    "Service Code": 73120,
    "Service Description": "X-ray of hand, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 89,
    "Service Category": "Radiology Services",
    "Service Code": 73130,
    "Service Description": "X-ray of hand, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 90,
    "Service Category": "Radiology Services",
    "Service Code": 73140,
    "Service Description": "X-ray of fingers, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 91,
    "Service Category": "Radiology Services",
    "Service Code": 73200,
    "Service Description": "CT scan of arm",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 92,
    "Service Category": "Radiology Services",
    "Service Code": 73218,
    "Service Description": "MRI scan of arm",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 93,
    "Service Category": "Radiology Services",
    "Service Code": 73220,
    "Service Description": "MRI scan of arm before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 94,
    "Service Category": "Radiology Services",
    "Service Code": 73221,
    "Service Description": "MRI scan of arm joint",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 95,
    "Service Category": "Radiology Services",
    "Service Code": 73222,
    "Service Description": "MRI scan of arm joint with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 96,
    "Service Category": "Radiology Services",
    "Service Code": 73223,
    "Service Description": "MRI scan of arm joint before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 97,
    "Service Category": "Radiology Services",
    "Service Code": 73501,
    "Service Description": "X-ray of hip with pelvis, 1 view",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 98,
    "Service Category": "Radiology Services",
    "Service Code": 73502,
    "Service Description": "X-ray of hip with pelvis, 2-3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 99,
    "Service Category": "Radiology Services",
    "Service Code": 73523,
    "Service Description": "X-ray of both hips with pelvis, minimum of 5 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 100,
    "Service Category": "Radiology Services",
    "Service Code": 73552,
    "Service Description": "X-ray of femur, minimum 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 101,
    "Service Category": "Radiology Services",
    "Service Code": 73560,
    "Service Description": "X-ray of knee, 1 or 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 102,
    "Service Category": "Radiology Services",
    "Service Code": 73562,
    "Service Description": "X-ray of knee, 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 103,
    "Service Category": "Radiology Services",
    "Service Code": 73565,
    "Service Description": "X-ray of both knees, standing, front to back view",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 104,
    "Service Category": "Radiology Services",
    "Service Code": 73590,
    "Service Description": "X-ray of lower leg, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 105,
    "Service Category": "Radiology Services",
    "Service Code": 73600,
    "Service Description": "X-ray of ankle, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 106,
    "Service Category": "Radiology Services",
    "Service Code": 73610,
    "Service Description": "X-ray of ankle, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 107,
    "Service Category": "Radiology Services",
    "Service Code": 73620,
    "Service Description": "X-ray of foot, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 108,
    "Service Category": "Radiology Services",
    "Service Code": 73630,
    "Service Description": "X-ray of foot, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 109,
    "Service Category": "Radiology Services",
    "Service Code": 73650,
    "Service Description": "X-ray of heel, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 110,
    "Service Category": "Radiology Services",
    "Service Code": 73660,
    "Service Description": "X-ray of toes, minimum of 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 111,
    "Service Category": "Radiology Services",
    "Service Code": 73700,
    "Service Description": "CT scan leg",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 112,
    "Service Category": "Radiology Services",
    "Service Code": 73702,
    "Service Description": "CT scan of leg before and after contrast injection",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 113,
    "Service Category": "Radiology Services",
    "Service Code": 73706,
    "Service Description": "CT scan of lower leg blood vessels with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 114,
    "Service Category": "Radiology Services",
    "Service Code": 73718,
    "Service Description": "MRI scan of leg",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 115,
    "Service Category": "Radiology Services",
    "Service Code": 73720,
    "Service Description": "MRI scan of leg before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 116,
    "Service Category": "Radiology Services",
    "Service Code": 73721,
    "Service Description": "MRI scan of leg joint",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 117,
    "Service Category": "Radiology Services",
    "Service Code": 73722,
    "Service Description": "MRI scan of leg joint with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 118,
    "Service Category": "Radiology Services",
    "Service Code": 73723,
    "Service Description": "MRI scan of leg joint before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 119,
    "Service Category": "Radiology Services",
    "Service Code": 74018,
    "Service Description": "X-ray of abdomen, 1 view",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 120,
    "Service Category": "Radiology Services",
    "Service Code": 74019,
    "Service Description": "X-ray of abdomen, 2 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 121,
    "Service Category": "Radiology Services",
    "Service Code": 74150,
    "Service Description": "CT scan abdomen",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 122,
    "Service Category": "Radiology Services",
    "Service Code": 74160,
    "Service Description": "CT scan abdomen with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 123,
    "Service Category": "Radiology Services",
    "Service Code": 74170,
    "Service Description": "CT scan abdomen before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 124,
    "Service Category": "Radiology Services",
    "Service Code": 74174,
    "Service Description":
      "CT scan of abdominal and pelvic blood vessels with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 125,
    "Service Category": "Radiology Services",
    "Service Code": 74175,
    "Service Description": "CT scan of abdominal blood vessels with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 126,
    "Service Category": "Radiology Services",
    "Service Code": 74176,
    "Service Description": "CT scan of abdomen and pelvis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 127,
    "Service Category": "Radiology Services",
    "Service Code": 74177,
    "Service Description": "CT scan of abdomen and pelvis with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 128,
    "Service Category": "Radiology Services",
    "Service Code": 74178,
    "Service Description":
      "CT scan of abdomen and pelvis before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 129,
    "Service Category": "Radiology Services",
    "Service Code": 74181,
    "Service Description": "MRI scan of abdomen",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 130,
    "Service Category": "Radiology Services",
    "Service Code": 74183,
    "Service Description": "MRI scan of abdomen before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 131,
    "Service Category": "Radiology Services",
    "Service Code": 74185,
    "Service Description": "MRI scan of blood vessels of abdomen",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 132,
    "Service Category": "Radiology Services",
    "Service Code": 74220,
    "Service Description": "X-ray of esophagus",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 133,
    "Service Category": "Radiology Services",
    "Service Code": 74221,
    "Service Description": "X-ray of esophagus with double contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 134,
    "Service Category": "Radiology Services",
    "Service Code": 74230,
    "Service Description": "X-ray for evaluation of swallowing function",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 135,
    "Service Category": "Radiology Services",
    "Service Code": 74240,
    "Service Description": "X-ray of upper digestive tract",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 136,
    "Service Category": "Radiology Services",
    "Service Code": 74246,
    "Service Description": "X-ray of upper digestive tract with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 137,
    "Service Category": "Radiology Services",
    "Service Code": 74250,
    "Service Description": "X-ray of small intestine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 138,
    "Service Category": "Radiology Services",
    "Service Code": 74261,
    "Service Description": "Diagnostic CT scan of large bowel",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 139,
    "Service Category": "Radiology Services",
    "Service Code": 74263,
    "Service Description": "Screening CT scan of large bowel",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 140,
    "Service Category": "Radiology Services",
    "Service Code": 74270,
    "Service Description": "X-ray of large bowel with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 141,
    "Service Category": "Radiology Services",
    "Service Code": 74300,
    "Service Description": "X-ray bile ducts/pancreas",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 142,
    "Service Category": "Radiology Services",
    "Service Code": 74400,
    "Service Description":
      "Imaging of urinary tract with injection of contrast into a vein",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 143,
    "Service Category": "Radiology Services",
    "Service Code": 74425,
    "Service Description": "X-ray of urinary tract",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 144,
    "Service Category": "Radiology Services",
    "Service Code": 74430,
    "Service Description": "X-ray of urinary bladder, minimum of 3 views",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 145,
    "Service Category": "Radiology Services",
    "Service Code": 74455,
    "Service Description": "X-ray urethra/bladder",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 146,
    "Service Category": "Radiology Services",
    "Service Code": 74740,
    "Service Description": "X-ray female genital tract",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 147,
    "Service Category": "Radiology Services",
    "Service Code": 75561,
    "Service Description": "MRI of heart before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 148,
    "Service Category": "Radiology Services",
    "Service Code": 75571,
    "Service Description":
      "CT scan of heart with evaluation of blood vessel calcium",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 149,
    "Service Category": "Radiology Services",
    "Service Code": 75574,
    "Service Description":
      "CT scan of heart blood vessels and grafts with contrast dye",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 150,
    "Service Category": "Radiology Services",
    "Service Code": 75635,
    "Service Description":
      "CT scan of abdominal aorta and both leg arteries with contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 151,
    "Service Category": "Radiology Services",
    "Service Code": 75989,
    "Service Description": "Abscess drainage under x-ray",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 152,
    "Service Category": "Radiology Services",
    "Service Code": 76000,
    "Service Description": "Imaging guidance for procedure, up to 1 hour",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 153,
    "Service Category": "Radiology Services",
    "Service Code": 76098,
    "Service Description": "X-ray of surgical specimen",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 154,
    "Service Category": "Radiology Services",
    "Service Code": 76377,
    "Service Description":
      "3D radiographic procedure with computerized image postprocessing",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 155,
    "Service Category": "Radiology Services",
    "Service Code": 76506,
    "Service Description": "Ultrasound of brain",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 156,
    "Service Category": "Radiology Services",
    "Service Code": 76536,
    "Service Description": "Ultrasound of head and neck",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 157,
    "Service Category": "Radiology Services",
    "Service Code": 76604,
    "Service Description": "Ultrasound of chest",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 158,
    "Service Category": "Radiology Services",
    "Service Code": 76641,
    "Service Description": "Ultrasound of one breast complete",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 159,
    "Service Category": "Radiology Services",
    "Service Code": 76642,
    "Service Description": "Ultrasound of one breast limited",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 160,
    "Service Category": "Radiology Services",
    "Service Code": 76700,
    "Service Description": "Ultrasound of abdomen",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 161,
    "Service Category": "Radiology Services",
    "Service Code": 76705,
    "Service Description": "Ultrasound of abdomen",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 162,
    "Service Category": "Radiology Services",
    "Service Code": 76706,
    "Service Description":
      "Ultrasound evaluation of abdominal aorta to detect bulging (aneurysm)",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 163,
    "Service Category": "Radiology Services",
    "Service Code": 76770,
    "Service Description": "Ultrasound behind abdominal cavity",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 164,
    "Service Category": "Radiology Services",
    "Service Code": 76775,
    "Service Description": "Ultrasound behind abdominal cavity, limited",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 165,
    "Service Category": "Radiology Services",
    "Service Code": 76800,
    "Service Description": "Ultrasound of spinal canal",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 166,
    "Service Category": "Radiology Services",
    "Service Code": 76801,
    "Service Description":
      "Abdominal ultrasound of pregnant uterus (less than 14 weeks 0 days) single or first fetus",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 167,
    "Service Category": "Radiology Services",
    "Service Code": 76805,
    "Service Description":
      "Abdominal ultrasound of pregnant uterus (greater or equal to 14 weeks 0 days) single or first fetus",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 168,
    "Service Category": "Radiology Services",
    "Service Code": 76815,
    "Service Description": "Ultrasound of pregnant uterus, 1 or more fetus(es)",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 169,
    "Service Category": "Radiology Services",
    "Service Code": 76817,
    "Service Description": "Vaginal ultrasound of pregnant uterus",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 170,
    "Service Category": "Radiology Services",
    "Service Code": 76830,
    "Service Description": "Ultrasound pelvis through vagina",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 171,
    "Service Category": "Radiology Services",
    "Service Code": 76831,
    "Service Description": "Ultrasound of uterus",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 172,
    "Service Category": "Radiology Services",
    "Service Code": 76856,
    "Service Description": "Ultrasound of pelvis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 173,
    "Service Category": "Radiology Services",
    "Service Code": 76857,
    "Service Description": "Ultrasound of pelvis limited",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 174,
    "Service Category": "Radiology Services",
    "Service Code": 76870,
    "Service Description": "US Testes",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 175,
    "Service Category": "Radiology Services",
    "Service Code": 76882,
    "Service Description": "Ultrasound of arm or leg",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 176,
    "Service Category": "Radiology Services",
    "Service Code": 76886,
    "Service Description": "Ultrasound of hips, infant",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 177,
    "Service Category": "Radiology Services",
    "Service Code": 76942,
    "Service Description": "Echo guide for biopsy",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 178,
    "Service Category": "Radiology Services",
    "Service Code": 77002,
    "Service Description": "Fluoroscopic guidance for insertion of needle",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 179,
    "Service Category": "Radiology Services",
    "Service Code": 77012,
    "Service Description": "CT scan for biopsy with needle",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 180,
    "Service Category": "Radiology Services",
    "Service Code": 77047,
    "Service Description": "MRI of both breasts",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 181,
    "Service Category": "Radiology Services",
    "Service Code": 77049,
    "Service Description": "MRI of both breasts before and after contrast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 182,
    "Service Category": "Radiology Services",
    "Service Code": 77065,
    "Service Description": "Mammography of one breast",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 183,
    "Service Category": "Radiology Services",
    "Service Code": 77066,
    "Service Description": "Mammography of both breasts for diagnosis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 184,
    "Service Category": "Radiology Services",
    "Service Code": 77067,
    "Service Description": "Mammography of both breasts for screening",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 185,
    "Service Category": "Radiology Services",
    "Service Code": 77072,
    "Service Description": "Imaging for bone age assessment",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 186,
    "Service Category": "Radiology Services",
    "Service Code": 77073,
    "Service Description": "Imaging for bone length assessment",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 187,
    "Service Category": "Radiology Services",
    "Service Code": 77075,
    "Service Description": "X-ray survey of forearm or wrist bone density",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 188,
    "Service Category": "Radiology Services",
    "Service Code": 77080,
    "Service Description":
      "Bone density measurement using dedicated X-ray machine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 189,
    "Service Category": "Radiology Services",
    "Service Code": 77081,
    "Service Description":
      "Bone density measurement using dedicated X-ray machine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 190,
    "Service Category": "Radiology Services",
    "Service Code": 78013,
    "Service Description": "Nuclear medicine imaging of thyroid",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 191,
    "Service Category": "Radiology Services",
    "Service Code": 78014,
    "Service Description":
      "Nuclear medicine imaging for thyroid uptake measurements",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 192,
    "Service Category": "Radiology Services",
    "Service Code": 78018,
    "Service Description": "NM Thyroid Carcinoma Mets Imaging Whole",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 193,
    "Service Category": "Radiology Services",
    "Service Code": 78070,
    "Service Description": "NM Parathyroid Study",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 194,
    "Service Category": "Radiology Services",
    "Service Code": 78195,
    "Service Description": "Imaging of lymphatic tissue and lymph node",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 195,
    "Service Category": "Radiology Services",
    "Service Code": 78226,
    "Service Description": "Imaging of liver and bile duct system",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 196,
    "Service Category": "Radiology Services",
    "Service Code": 78264,
    "Service Description": "Stomach emptying study",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 197,
    "Service Category": "Radiology Services",
    "Service Code": 78300,
    "Service Description": "Bone and/or joint imaging",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 198,
    "Service Category": "Radiology Services",
    "Service Code": 78306,
    "Service Description": "Bone and/or joint imaging, whole body",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 199,
    "Service Category": "Radiology Services",
    "Service Code": 78315,
    "Service Description": "Bone and/or joint imaging, 3 phase study",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 200,
    "Service Category": "Radiology Services",
    "Service Code": 78451,
    "Service Description":
      "Nuclear medicine study of vessels of heart using drugs or exercise single study",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 201,
    "Service Category": "Radiology Services",
    "Service Code": 78452,
    "Service Description":
      "Nuclear medicine study of vessels of heart using drugs or exercise multiple studies",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 202,
    "Service Category": "Radiology Services",
    "Service Code": 78582,
    "Service Description":
      "Nuclear medicine study of lung ventilation and blood circulation in the lungs",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 203,
    "Service Category": "Radiology Services",
    "Service Code": 78597,
    "Service Description":
      "Nuclear medicine study with measurement of blood circulation in the lungs",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 204,
    "Service Category": "Radiology Services",
    "Service Code": 78608,
    "Service Description":
      "Nuclear medicine study brain with metabolic evaluation",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 205,
    "Service Category": "Radiology Services",
    "Service Code": 78707,
    "Service Description":
      "Nuclear medicine study of kidney with assessment of blood flow and function",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 206,
    "Service Category": "Radiology Services",
    "Service Code": 78708,
    "Service Description":
      "Nuclear medicine study of kidney with assessment of blood flow and function",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 207,
    "Service Category": "Radiology Services",
    "Service Code": 78803,
    "Service Description":
      "Nuclear medicine study of radioactive material distribution",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 208,
    "Service Category": "Radiology Services",
    "Service Code": 78814,
    "Service Description": "Nuclear medicine study with CT imaging",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 209,
    "Service Category": "Radiology Services",
    "Service Code": 78815,
    "Service Description":
      "Nuclear medicine study with CT imaging skull base to mid-thigh",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 210,
    "Service Category": "Radiology Services",
    "Service Code": 78816,
    "Service Description": "Nuclear medicine study with CT imaging whole body",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 211,
    "Service Category": "Radiology Services",
    "Service Code": 78831,
    "Service Description":
      "Nuclear medicine marking of tumor or inflammation in 2 or more areas, or 1 area over multiple days",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 212,
    "Service Category": "Radiology Services",
    "Service Code": 79101,
    "Service Description": "Radioactive material therapy into vein",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 80048,
    "Service Description": "Blood test, basic group of blood chemicals",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 80053,
    "Service Description": "Blood test, comprehensive group of blood chemicals",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 80061,
    "Service Description": "Blood test, lipids (cholesterol and triglycerides)",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 4,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 80069,
    "Service Description": "Kidney function blood test panel",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 5,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 80076,
    "Service Description": "Liver function blood test panel",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 6,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 81000,
    "Service Description":
      "Manual urinalysis test with examination using microscope nonauto",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 7,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 81001,
    "Service Description":
      "Manual urinalysis test with examination using microscope auto",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 8,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 81002,
    "Service Description": "Urinalysis, manual test",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 9,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 81003,
    "Service Description": "Automated urinalysis test",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 10,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 84153,
    "Service Description": "PSA (prostate specific antigen) measurement",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 11,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 84154,
    "Service Description": "PSA (prostate specific antigen) measurement",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 12,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 84443,
    "Service Description": "Blood test, thyroid stimulating hormone (TSH)",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 13,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 85025,
    "Service Description":
      "Complete blood cell count (red cells, white blood cell, platelets), automated test w/auto differential white blood count",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 14,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 85027,
    "Service Description":
      "Complete blood cell count (red cells, white blood cell, platelets), automated test",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 15,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 85610,
    "Service Description": "Blood test, clotting time",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 16,
    "Service Category": "Pathology & Laboratory",
    "Service Code": 85730,
    "Service Description": "Coagulation assessment blood test",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "A",
    "Service Code": 97110,
    "Service Description":
      "Therapeutic exercise to develop strength, endurance, range of motion, and flexibility, each 15 minutes",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Outpatient Surgery",
    "Service Code": 19120,
    "Service Description": "Removal of 1 or more breast growth, open procedure",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Outpatient Surgery",
    "Service Code": 20206,
    "Service Description": "Needle biopsy of muscle, accessed through the skin",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Outpatient Surgery",
    "Service Code": 20610,
    "Service Description":
      "Aspiration and/or injection of large joint or joint capsule",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 4,
    "Service Category": "Outpatient Surgery",
    "Service Code": 22551,
    "Service Description":
      "Fusion of spine bones with removal of disc at upper spinal column, anterior approach",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 5,
    "Service Category": "Outpatient Surgery",
    "Service Code": 22853,
    "Service Description":
      "Insertion of device into intervertebral disc space of spine and fusion of vertebrae",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 6,
    "Service Category": "Outpatient Surgery",
    "Service Code": 27130,
    "Service Description": "Replacement of thigh bone and hip joint prosthesis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 7,
    "Service Category": "Outpatient Surgery",
    "Service Code": 29826,
    "Service Description": "Shoulder arthroscopy/surgery",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 8,
    "Service Category": "Outpatient Surgery",
    "Service Code": 29827,
    "Service Description": "Repair of shoulder rotator cuff using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 9,
    "Service Category": "Outpatient Surgery",
    "Service Code": 29828,
    "Service Description":
      "Release of shoulder biceps tendon using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 10,
    "Service Category": "Outpatient Surgery",
    "Service Code": 29880,
    "Service Description": "Removal of both knee cartilages using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 11,
    "Service Category": "Outpatient Surgery",
    "Service Code": 29881,
    "Service Description": "Knee arthroscopy/surgery",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 12,
    "Service Category": "Outpatient Surgery",
    "Service Code": 31253,
    "Service Description":
      "Complete examination of nose and sinuses using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 13,
    "Service Category": "Outpatient Surgery",
    "Service Code": 37243,
    "Service Description":
      "Occlusion of tumors or obstructed blood vessel with radiological supervision and interpretation, roadmapping, and imaging guidance",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 14,
    "Service Category": "Outpatient Surgery",
    "Service Code": 42820,
    "Service Description": "Remove tonsils and adenoids",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 15,
    "Service Category": "Outpatient Surgery",
    "Service Code": 42821,
    "Service Description":
      "Removal of tonsils and adenoid glands patient age 12 or over",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 16,
    "Service Category": "Outpatient Surgery",
    "Service Code": 42826,
    "Service Description": "Removal of tonsils patient age 12 or over",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 17,
    "Service Category": "Outpatient Surgery",
    "Service Code": 42830,
    "Service Description": "Removal of adenoids patient younger than age 12",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 18,
    "Service Category": "Outpatient Surgery",
    "Service Code": 43235,
    "Service Description":
      "Diagnostic examination of esophagus, stomach, and/or upper small bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 19,
    "Service Category": "Outpatient Surgery",
    "Service Code": 43237,
    "Service Description":
      "Ultrasound examination of esophagus, stomach, and/or upper small bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 20,
    "Service Category": "Outpatient Surgery",
    "Service Code": 43238,
    "Service Description":
      "Ultrasound guided needle aspiration or biopsies of esophagus using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 21,
    "Service Category": "Outpatient Surgery",
    "Service Code": 43239,
    "Service Description":
      "Biopsy of the esophagus, stomach, and/or upper small bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 22,
    "Service Category": "Outpatient Surgery",
    "Service Code": 43244,
    "Service Description":
      "Tying of dilated veins of stomach and/or esophagus using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 23,
    "Service Category": "Outpatient Surgery",
    "Service Code": 43247,
    "Service Description":
      "Removal of foreign bodies of esophagus, stomach, and/or upper small bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 24,
    "Service Category": "Outpatient Surgery",
    "Service Code": 44970,
    "Service Description": "Removal of appendix using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 25,
    "Service Category": "Outpatient Surgery",
    "Service Code": 45378,
    "Service Description": "Diagnostic colonoscopy",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 26,
    "Service Category": "Outpatient Surgery",
    "Service Code": 45380,
    "Service Description": "Colonoscopy and biopsy",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 27,
    "Service Category": "Outpatient Surgery",
    "Service Code": 45381,
    "Service Description": "Injections of large bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 28,
    "Service Category": "Outpatient Surgery",
    "Service Code": 45385,
    "Service Description":
      "Removal of polyps or growths of large bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 29,
    "Service Category": "Outpatient Surgery",
    "Service Code": 45391,
    "Service Description":
      "Ultrasound examination of lower large bowel using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 30,
    "Service Category": "Outpatient Surgery",
    "Service Code": 47000,
    "Service Description": "Needle biopsy of liver, accessed through the skin",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 31,
    "Service Category": "Outpatient Surgery",
    "Service Code": 47562,
    "Service Description": "Removal of gallbladder using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 32,
    "Service Category": "Outpatient Surgery",
    "Service Code": 49083,
    "Service Description":
      "Drainage of fluid from abdominal cavity using imaging guidance",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 33,
    "Service Category": "Outpatient Surgery",
    "Service Code": 49505,
    "Service Description":
      "Repair of groin hernia patient age 5 years or older",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 34,
    "Service Category": "Outpatient Surgery",
    "Service Code": 49650,
    "Service Description": "Repair of groin hernia using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 35,
    "Service Category": "Outpatient Surgery",
    "Service Code": 55700,
    "Service Description": "Biopsy of prostate gland",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 36,
    "Service Category": "Outpatient Surgery",
    "Service Code": 55866,
    "Service Description":
      "Surgical removal of prostate and surrounding lymph nodes using an endoscope",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 37,
    "Service Category": "Outpatient Surgery",
    "Service Code": 60500,
    "Service Description": "Removal or exploration of parathyroid glands",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 38,
    "Service Category": "Outpatient Surgery",
    "Service Code": 62270,
    "Service Description": "Spinal tap for diagnosis",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 39,
    "Service Category": "Outpatient Surgery",
    "Service Code": 62322,
    "Service Description":
      "Injection of substance into spinal canal of lower back or sacrum",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 40,
    "Service Category": "Outpatient Surgery",
    "Service Code": 62323,
    "Service Description":
      "Injection of substance into spinal canal of lower back or sacrum using imaging guidance",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 41,
    "Service Category": "Outpatient Surgery",
    "Service Code": 64483,
    "Service Description":
      "Injections of anesthetic and/or steroid drug into lower or sacral spine nerve root using imaging guidance",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 42,
    "Service Category": "Outpatient Surgery",
    "Service Code": 66821,
    "Service Description":
      "Removal of recurring cataract in lens capsule using laser",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 43,
    "Service Category": "Outpatient Surgery",
    "Service Code": 66984,
    "Service Description": "Removal of cataract with insertion of lens",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Other",
    "Service Code": 90834,
    "Service Description":
      "Psychotherapy, 45 minutes with patient and/or family member",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Other",
    "Service Code": 90847,
    "Service Description": "Family psychotherapy including patient",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Other",
    "Service Code": 90853,
    "Service Description": "Group psychotherapy",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Neurology & Sleep",
    "Service Code": 95810,
    "Service Description":
      "Sleep monitoring of patient (6 years or older) in sleep lab",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Inpatient",
    "Service Code": 217,
    "Service Description":
      "CARDIAC VALVE & OTH MAJ CARDIOTHORACIC PROC W CARD CATH W MCC Non-ST elevation (NSTEMI) myocardial infarction",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Inpatient",
    "Service Code": 217,
    "Service Description":
      "Replacement of left lower heart chamber valve using artificial valve on heart-lung machine",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Inpatient",
    "Service Code": 460,
    "Service Description":
      "Spinal fusion except cervical w/o MCC Fusion of Lumbar Vertebral Joint with Synthetic Substitute, Posterior Approach, Posterior Column, Op Spondylolysis, site unspecified",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 4,
    "Service Category": "Inpatient",
    "Service Code": 470,
    "Service Description":
      "Major joint replacement or reattachment of lower extremity w/o MCC Replacement of Right Knee Joint with Autologous Tissue Substitute, Open Approach Osteoarthritis of knee, unspecified",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 5,
    "Service Category": "Inpatient",
    "Service Code": 473,
    "Service Description":
      "Cervical spinal fusion w/o CC/MCC Fusion of Cervical Vertebral Joint with Autologous Tissue Substitute, Anterior Approach, Anterior Co Spinal stenosis, cervical region",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 6,
    "Service Category": "Inpatient",
    "Service Code": 775,
    "Service Description":
      "Obstetrical pre- and postpartum care and vaginal delivery",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 7,
    "Service Category": "Inpatient",
    "Service Code": 806,
    "Service Description": "Vaginal delivery after prior cesarean delivery",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 8,
    "Service Category": "Inpatient",
    "Service Code": "O34.29",
    "Service Description":
      "Uterine & adnexa proc for non-malignancy w/o CC/MCC Resection of Cervix, Percutaneous Endoscopic Approach Leiomyoma of uterus, unspecified",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 9,
    "Service Category": "Inpatient",
    "Service Code": "O48.0",
    "Service Description": "Cesarian delivery with pre- and post-delivery care",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Cardiovascular",
    "Service Code": 93005,
    "Service Description":
      "Routine electrocardiogram (EKG) with tracing using at least 12 leads",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 2,
    "Service Category": "Cardiovascular",
    "Service Code": 93017,
    "Service Description":
      "Exercise or drug-induced heart and blood vessel stress test with EKG tracing and monitoring",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 3,
    "Service Category": "Cardiovascular",
    "Service Code": 93306,
    "Service Description":
      "Ultrasound examination of heart including color-depicted blood flow rate, direction, and valve function",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 4,
    "Service Category": "Cardiovascular",
    "Service Code": 93307,
    "Service Description": "Chest ultrasound examination of heart",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 5,
    "Service Category": "Cardiovascular",
    "Service Code": 93350,
    "Service Description":
      "Ultrasound examination of the heart performed during rest, exercise, and/or drug-induced stress with interpretation and report",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 6,
    "Service Category": "Cardiovascular",
    "Service Code": "Not Specified",
    "Service Description":
      "Insertion of catheter into left heart including imaging interpretation and supervision and injection",
    Price: "$456",
    Remarks: "",
  },
  {
    No: 1,
    "Service Category": "Audiology",
    "Service Code": 92611,
    "Service Description":
      "Fluoroscopic and video recorded motion evaluation of swallowing function",
    Price: "$456",
    Remarks: "",
  },
];
